### ISSUE TITLE
small bug with envied

### ISSUE THREAD

**Issue by mavriq-dev** [bizz84/tmdb_movie_app_riverpod#13]
using TMDBKEY with an underscore causes the build runner to throw and error:

```
[SEVERE] envied_generator:envied on lib/env/env.dart (cached):

Environment variable not found for field `tmdbApiKey`.
package:tmdb_movie_app_riverpod/env/env.dart:8:23
  ╷
8 │   static final String tmdbApiKey = _Env.tmdbApiKey;
  │                       ^^^^^^^^^^
  ╵
[SEVERE] Failed after 122ms
```

Removing the underscore in the .env file and envied.dart allows the runner to complete.

**Comment by kunalparmar5** [comment]
Hello Sir , I am getting these errors 
lib/env/env.dart:3:6: Error: Error when reading 'lib/env/env.g.dart': The system cannot find the file specified.

part 'env.g.dart';
     ^
lib/env/env.dart:3:6: Error: Can't use 'lib/env/env.g.dart' as a part, because it has no 'part of' declaration.
part 'env.g.dart';
     ^
lib/env/env.dart:9:51: Error: The setter 'TMDB_KEY' isn't defined for the class 'Envied'.
 - 'Envied' is from 'package:envied/src/envied_base.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/envied-0.5.4+1/lib/src/envied_base.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'TMDB_KEY'.
static final String tmdbApiKey = const Envied().  TMDB_KEY = 'cafd788865ebd672f71bbc02c81d8e4c';
                                                  ^^^^^^^^
Target kernel_snapshot failed: Exception

could you please help

**Comment by bizz84** [comment]
@kunalparmar5 have you followed the instructions and ran the code generator [as instructed in the README](https://github.com/bizz84/tmdb_movie_app_riverpod?tab=readme-ov-file#getting-a-tmdb-api-key-and-running-the-project)?

**Comment by bizz84** [comment]
@mavriq-dev This project has been updated recently and now uses the latest package versions.

Closing as this issue no longer happens for me. But feel free to open a new one if you still have this problem.
